<%@ Page Language="C#" AutoEventWireup="true" CodeFile="RadGridDemo.aspx.cs" Inherits="RadGridDemo" %>

<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
        <asp:SqlDataSource ID="SQLParent" runat="server" ConnectionString="<%$ ConnectionStrings:trainingConnectionString %>" SelectCommand="SELECT [ParentID], [Name], [Age], [Gender] FROM [Parent] WHERE ([Name] LIKE '%' + @Name + '%')" ConflictDetection="CompareAllValues" DeleteCommand="DELETE FROM [Parent] WHERE [ParentID] = @original_ParentID AND (([Name] = @original_Name) OR ([Name] IS NULL AND @original_Name IS NULL)) AND (([Age] = @original_Age) OR ([Age] IS NULL AND @original_Age IS NULL)) AND (([Gender] = @original_Gender) OR ([Gender] IS NULL AND @original_Gender IS NULL))" InsertCommand="INSERT INTO [Parent] ([ParentID], [Name], [Age], [Gender]) VALUES (@ParentID, @Name, @Age, @Gender)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [Parent] SET [Name] = @Name, [Age] = @Age, [Gender] = @Gender WHERE [ParentID] = @original_ParentID AND (([Name] = @original_Name) OR ([Name] IS NULL AND @original_Name IS NULL)) AND (([Age] = @original_Age) OR ([Age] IS NULL AND @original_Age IS NULL)) AND (([Gender] = @original_Gender) OR ([Gender] IS NULL AND @original_Gender IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_ParentID" Type="Int32" />
                <asp:Parameter Name="original_Name" Type="String" />
                <asp:Parameter Name="original_Age" Type="Int32" />
                <asp:Parameter Name="original_Gender" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="ParentID" Type="Int32" />
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Age" Type="Int32" />
                <asp:Parameter Name="Gender" Type="String" />
            </InsertParameters>
            <SelectParameters>
                <asp:ControlParameter ControlID="TxtSearchName" Name="Name" PropertyName="Text" Type="String" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Age" Type="Int32" />
                <asp:Parameter Name="Gender" Type="String" />
                <asp:Parameter Name="original_ParentID" Type="Int32" />
                <asp:Parameter Name="original_Name" Type="String" />
                <asp:Parameter Name="original_Age" Type="Int32" />
                <asp:Parameter Name="original_Gender" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <telerik:RadScriptManager ID="RadScriptManager1" Runat="server">
        </telerik:RadScriptManager>
        Search : Name<br />
        <asp:TextBox ID="TxtSearchName" runat="server"></asp:TextBox>
        <br />
        <asp:Button ID="BtnSearch" runat="server" Text="search!" />
        <br />
        <telerik:RadGrid ID="RGridParent" runat="server" AllowFilteringByColumn="True" AllowPaging="True" DataSourceID="SQLParent" GroupPanelPosition="Top" OnItemDataBound="RGridParent_ItemDataBound" AutoGenerateDeleteColumn="true">
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
            <MasterTableView AutoGenerateColumns="False" DataKeyNames="ParentID" DataSourceID="SQLParent" AllowAutomaticDeletes="true">
                <PagerStyle AlwaysVisible="true" />
                <Columns>
                    <telerik:GridBoundColumn DataField="ParentID" DataType="System.Int32" FilterControlAltText="Filter ParentID column" HeaderText="ParentID" ReadOnly="True" SortExpression="ParentID" UniqueName="ParentID">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Name" FilterControlAltText="Filter Name column" HeaderText="Name" SortExpression="Name" UniqueName="Name">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Age" DataType="System.Int32" FilterControlAltText="Filter Age column" HeaderText="Age" SortExpression="Age" UniqueName="Age">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Gender" FilterControlAltText="Filter Gender column" HeaderText="Gender" SortExpression="Gender" UniqueName="Gender">
                    </telerik:GridBoundColumn>
                    <telerik:GridTemplateColumn>
                        <ItemTemplate>
                            <asp:HyperLink ID="LnkEdit" runat="server" Text="Edit"></asp:HyperLink>
                        </ItemTemplate>
                    </telerik:GridTemplateColumn>
                </Columns>
            </MasterTableView>
        </telerik:RadGrid>
        <p>
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Add!" />
        </p>
    </form>
</body>
</html>
